### ISSUE TITLE
Issue with Evaluating string: "CiInitialize"

### ISSUE THREAD

**Issue by jorgeaduran** [marirs/capa-rs#3]
[disable-driver-code-integrity.yml](https://github.com/mandiant/capa-rules/blob/48dfd001d8dd472c67246360b685094a5830f8b9/host-interaction/driver/disable-driver-code-integrity.yml#L4)

**Comment by jorgeaduran** [comment]
I've identified a potential solution to this bug. The issue seems to be that the evaluate method is attempting to find a match including the "description", which hinders the matching process. For instance:
key=String(StringFeature { value: "CiInitialize", description: "" })
versus
self=StringFeature { value: "CiInitialize", description: "exported symbol name used to resolve code integrity configuration" }.
This discrepancy causes the matching to fail. However, by modifying the evaluate method of StringFeature as shown below, it can successfully detect matches:
```
pub fn evaluate(
        &self,
        features: &std::collections::HashMap<Feature, Vec<u64>>,
    ) -> Result<(bool, Vec<u64>)> {
        for (key, addresses) in features {
            if let Feature::String(feature_string) = key {
                if feature_string.value == self.value {
                    return Ok((true, addresses.clone()));
                }
            }
        }
        Ok((false, vec![]))
    }
```
This code iterates through the features and compares the values, ignoring the description, which resolves the issue.

**Comment by marirs** [comment]
@jorgeaduran  - Thanks so much for checking this out.
Let me check this out over this week end, and get something fixed!

Thanks again to bring this up.

**Comment by jorgeaduran** [comment]
:) thank you very much for maintaining it. We must also consider new parameters of the rules such as the Call scope

[stop service](https://github.com/mandiant/capa-rules/blob/48dfd001d8dd472c67246360b685094a5830f8b9/host-interaction/service/stop/stop-service.yml)

**Comment by marirs** [comment]
I'll check on the new rules as well.

**Comment by jorgeaduran** [comment]
By the way, in the case of stop-service we are not taking the number 0x1 STOP_SERVICE, the function controlservice is detected but not the Number, possibly we have to add logic to disassemble in tail call analyzer(finalize_function).
![image](https://github.com/marirs/capa-rs/assets/17909162/22e074ea-3acf-4b7a-a64a-1b10900e8d74)

**Comment by jorgeaduran** [comment]
Thank you very much for updating the yml parsing, now we need to update the smda to correct what I mentioned in the screenshot above :) "add logic to disassemble in tail call analyzer(finalize_function)."
