### ISSUE TITLE
- smda extractor fails

### ISSUE THREAD

**Issue by jorgeaduran** [marirs/capa-rs#5]
After reviewing the code I think it is being done wrong to subtract the image base from the RVA in the extract_file_export_names function,
instead of *o as u64 - self.get_base_address()?, I think you should use *o as u64 directly, if necessary you would have to make sure that the RVA falls within the image

**Comment by marirs** [comment]
Thanks so much @jorgeaduran  for your code! Really appreciate them.
Shall I close this?

**Comment by jorgeaduran** [comment]
@marirs It's a pleasure, if it can be closed now, thank you!
